name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  # Allows to run this via the Actions tab
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Check if source is affected
        id: source-affected
        uses: dorny/paths-filter@v2
        with:
          filters: |
            src:
              - 'src/**'
              - 'build.gradle'

    outputs:
      sourceAffected: ${{ steps.source-affected.outputs.src }}

  lint:
    needs: setup
    if: ${{ needs.setup.outputs.sourceAffected == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: Lint the code
        uses: gradle/gradle-build-action@v2
        with:
          arguments: lintGradle generateGradleLintReport

      - name: Save lint report
        continue-on-error: true
        uses: actions/upload-artifact@v3
        with:
          name: lint-report
          path: ./build/reports/gradleLint/sts-kafka-sink.html

  test:
    needs:
      - setup
      - lint
    if: ${{ needs.setup.outputs.sourceAffected == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: Verify(?) the code
        uses: gradle/gradle-build-action@v2
        with:
          arguments: check

      - name: Test the code
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test

      - name: Save test report
        continue-on-error: true
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: ./build/reports/tests/test
